import type { Session } from "./types";

/**
 * Les 6 séances du split (Bloc 1, jours 1–25), source de vérité pour tous les
 * blocs. Le Bloc 2 réutilise ces séances en affichant les techniques
 * d'intensification (`intensification`).
 */
export const SESSIONS: Record<string, Session> = {
    "poussee-a": {
        dayType: "poussee-a",
        title: "Poussée A",
        focus: "Pecs, épaules, triceps",
        exercises: [
            {
                key: "pompes-declinees",
                name: "Pompes déclinées (pieds sur chaise)",
                sets: "4",
                reps: "8–15",
                notes: "Haut des pecs + delts antérieurs.",
                lexiconKey: "pompes-declinees",
                intensification:
                    "Dropset mécanique (1×/séance) : déclinées → standards → genoux, à l'échec à chaque étape.",
            },
            {
                key: "dips-chaises",
                name: "Dips entre deux chaises",
                sets: "3",
                reps: "8–15",
                notes: "Buste penché vers l'avant.",
                lexiconKey: "dips-chaises",
                intensification: "Rest-pause sur la dernière série : échec → 15 s → max → 15 s → max.",
            },
            {
                key: "pompes-standards",
                name: "Pompes standards",
                sets: "3",
                reps: "max −1",
                notes: "Volume pecs.",
                lexiconKey: "pompes-standards",
            },
            {
                key: "developpe-epaules-bande",
                name: "Développé épaules à la bande",
                sets: "3",
                reps: "10–15",
                band: "20 kg",
                notes: "Debout sur la bande, pousse au-dessus de la tête. Commence 20 kg.",
                lexiconKey: "developpe-epaules-bande",
            },
            {
                key: "extension-triceps-oh",
                name: "Extension triceps au-dessus de la tête à la bande",
                sets: "3",
                reps: "12–15",
                band: "10 kg",
                notes: "Chef long en étirement.",
                lexiconKey: "extension-triceps-oh",
                intensification: "Dropset bande : à l'échec, passe à la 10 kg et va au max.",
            },
            {
                key: "pompes-diamant",
                name: "Pompes diamant",
                sets: "2",
                reps: "max",
                notes: "Finisher triceps.",
                lexiconKey: "pompes-diamant",
            },
        ],
    },

    "tirage-a": {
        dayType: "tirage-a",
        title: "Tirage A",
        focus: "Largeur du dos, biceps",
        exercises: [
            {
                key: "tractions-pronation",
                name: "Tractions pronation",
                sets: "4",
                reps: "max (objectif 5–10)",
                band: "assist. 30 kg",
                notes: "Assistance bande 30 kg sous les pieds/genoux au début. Le roi du V.",
                lexiconKey: "tractions",
                intensification: "Rest-pause sur la dernière série : échec → 15 s → max → 15 s → max.",
            },
            {
                key: "rowing-inverse",
                name: "Rowing inversé sous la table",
                sets: "4",
                reps: "8–15",
                notes: "Pieds surélevés pour durcir.",
                lexiconKey: "rowing-inverse",
            },
            {
                key: "tirage-bande-assis",
                name: "Tirage à la bande assis",
                sets: "3",
                reps: "10–15",
                band: "30 kg ou 20+10",
                notes: "Tire vers le ventre, serre les omoplates.",
                lexiconKey: "tirage-bande-assis",
            },
            {
                key: "face-pull",
                name: "Face pull à la bande",
                sets: "3",
                reps: "15–20",
                band: "10 kg",
                notes: "Santé d'épaule non négociable.",
                lexiconKey: "face-pull",
            },
            {
                key: "curl-bande",
                name: "Curl à la bande",
                sets: "3",
                reps: "10–15",
                band: "20 kg",
                notes: "Raccourcis pour durcir.",
                lexiconKey: "curl-bande",
                intensification: "Myo-reps ou dropset : à l'échec sur la 20 kg, attrape la 10 kg et va au max.",
            },
            {
                key: "curl-marteau",
                name: "Curl marteau à la bande",
                sets: "2",
                reps: "12–15",
                band: "10–20 kg",
                lexiconKey: "curl-marteau",
                intensification: "Myo-reps ou dropset bande à l'échec.",
            },
        ],
    },

    jambes: {
        dayType: "jambes",
        title: "Jambes + abdos",
        focus: "Équilibre",
        exercises: [
            {
                key: "squat-bulgare",
                name: "Squat bulgare (pied arrière sur chaise)",
                sets: "4",
                reps: "10–15/jambe",
                lexiconKey: "squat-bulgare",
            },
            {
                key: "pistol-squat",
                name: "Progression pistol squat (assisté au cadre de porte)",
                sets: "3",
                reps: "5–10/jambe",
                lexiconKey: "pistol-squat",
            },
            {
                key: "good-morning",
                name: "Good morning / soulevé roumain à la bande",
                sets: "3",
                reps: "12–15",
                band: "30 kg+",
                lexiconKey: "good-morning",
            },
            {
                key: "pont-fessier-unilateral",
                name: "Pont fessier à une jambe",
                sets: "3",
                reps: "12–15/jambe",
                lexiconKey: "pont-fessier-unilateral",
            },
            {
                key: "mollets",
                name: "Mollets une jambe sur une marche",
                sets: "3",
                reps: "12–20/jambe",
                lexiconKey: "mollets",
            },
            {
                key: "releves-jambes",
                name: "Relevés de jambes suspendu à la barre",
                sets: "3",
                reps: "8–15",
                lexiconKey: "releves-jambes",
            },
            {
                key: "crunch-bande",
                name: "Crunch à la bande (ancrée en bas de porte, à genoux)",
                sets: "3",
                reps: "12–15",
                lexiconKey: "crunch-bande",
            },
        ],
    },

    "poussee-b": {
        dayType: "poussee-b",
        title: "Poussée B ⭐",
        focus: "Deltoïdes latéraux (priorité n° 1)",
        exercises: [
            {
                key: "pike-push-ups",
                name: "Pike push-ups",
                sets: "4",
                reps: "6–12",
                notes: "Progression : pieds sur chaise → mur.",
                lexiconKey: "pike-push-ups",
                intensification: "Rest-pause sur la dernière série : échec → 15 s → max → 15 s → max.",
            },
            {
                key: "elevations-laterales",
                name: "Élévations latérales à la bande (un bras à la fois)",
                sets: "5",
                reps: "12–20",
                band: "10 kg",
                notes: "Exercice n° 1 de ta largeur. Progression : raccourcir → 20 kg.",
                lexiconKey: "elevations-laterales",
                intensification:
                    "Myo-reps : active 15–20 reps près de l'échec, puis 4 × 5 avec 15 s de repos. Ou dropset 20 → 10 kg.",
            },
            {
                key: "pompes-pseudo-planche",
                name: "Pompes pseudo-planche (mains vers les hanches)",
                sets: "3",
                reps: "6–12",
                notes: "Delts antérieurs lourds.",
                lexiconKey: "pompes-pseudo-planche",
            },
            {
                key: "upright-row",
                name: "Tirage vertical à la bande, coudes hauts (upright row)",
                sets: "3",
                reps: "12–15",
                notes: "2e angle deltoïde latéral.",
                lexiconKey: "upright-row",
            },
            {
                key: "extension-triceps-oh",
                name: "Extension triceps au-dessus de la tête à la bande",
                sets: "3",
                reps: "12–15",
                notes: "2e dose hebdo.",
                lexiconKey: "extension-triceps-oh",
                intensification: "Dropset bande : à l'échec, passe à une bande plus légère et va au max.",
            },
            {
                key: "shrugs",
                name: "Shrugs à la bande",
                sets: "3",
                reps: "15–20",
                band: "30 kg",
                notes: "Trapèzes.",
                lexiconKey: "shrugs",
            },
        ],
    },

    "tirage-b": {
        dayType: "tirage-b",
        title: "Tirage B + bras",
        focus: "Dos, bras, avant-bras",
        exercises: [
            {
                key: "tractions-neutre-supination",
                name: "Tractions prise neutre ou supination",
                sets: "4",
                reps: "max (assistées si besoin)",
                lexiconKey: "tractions",
                intensification: "Rest-pause sur la dernière série : échec → 15 s → max → 15 s → max.",
            },
            {
                key: "rowing-inverse-pieds-sureleves",
                name: "Rowing inversé, pieds surélevés",
                sets: "3",
                reps: "6–12",
                lexiconKey: "rowing-inverse",
            },
            {
                key: "pull-over-bande",
                name: "Pull-over à la bande",
                sets: "3",
                reps: "12–15",
                notes: "Ancrée en haut, bras tendus, tire vers les hanches.",
                lexiconKey: "pull-over-bande",
            },
            {
                key: "curl-bande-lourd",
                name: "Curl à la bande, lourd",
                sets: "3",
                reps: "8–12",
                band: "20 kg raccourcie ou 30 kg",
                lexiconKey: "curl-bande",
                intensification: "Myo-reps ou dropset : à l'échec, passe à une bande plus légère et va au max.",
            },
            {
                key: "curl-concentre",
                name: "Curl concentré à la bande",
                sets: "2",
                reps: "12–15/bras",
                notes: "Sous le pied, buste penché.",
                lexiconKey: "curl-concentre",
                intensification: "Échec complet autorisé.",
            },
            {
                key: "curl-inverse",
                name: "Curl inversé à la bande",
                sets: "2",
                reps: "12–15",
                lexiconKey: "curl-inverse",
                intensification: "Échec complet autorisé.",
            },
            {
                key: "dead-hang",
                name: "Suspension à la barre (dead hang)",
                sets: "3",
                reps: "max s",
                notes: "Avant-bras + poigne, gratuit.",
                lexiconKey: "dead-hang",
            },
            {
                key: "elevations-buste-penche",
                name: "Élévations buste penché à la bande (delt postérieur)",
                sets: "3",
                reps: "15–20",
                lexiconKey: "elevations-buste-penche",
            },
        ],
    },

    pump: {
        dayType: "pump",
        title: "Pump complet + corde",
        focus: "3e stimulation",
        isCircuit: true,
        circuitNote: "Circuit : 3 tours, 60 s de repos entre les tours.",
        finisher:
            "Termine par 8–10 rounds de corde à sauter : 40 s effort / 20 s repos (conditionnement + définition abdos sans gruger la récupération).",
        exercises: [
            {
                key: "pump-pompes",
                name: "Pompes",
                sets: "3 tours",
                reps: "max −2",
                lexiconKey: "pompes-standards",
            },
            {
                key: "pump-tractions",
                name: "Tractions",
                sets: "3 tours",
                reps: "max −1",
                lexiconKey: "tractions",
            },
            {
                key: "pump-pike",
                name: "Pike push-ups",
                sets: "3 tours",
                reps: "max −2",
                lexiconKey: "pike-push-ups",
            },
            {
                key: "pump-elevations",
                name: "Élévations latérales à la bande",
                sets: "3 tours",
                reps: "15–20",
                lexiconKey: "elevations-laterales",
            },
            {
                key: "pump-rowing",
                name: "Rowing inversé sous la table",
                sets: "3 tours",
                reps: "max −2",
                lexiconKey: "rowing-inverse",
            },
            {
                key: "pump-crunch",
                name: "Crunch à la bande",
                sets: "3 tours",
                reps: "15",
                lexiconKey: "crunch-bande",
            },
        ],
    },

    repos: {
        dayType: "repos",
        title: "Repos",
        focus: "Récupération (cruiser board bienvenu)",
        exercises: [],
    },
};
